### PR TITLE
Fix search bar bugs

### LINKED ISSUE #274: Fixes to the homepage and searchbar
## Describe the bug

- [x] Fix the defaults for the price filters should be null, rather than zero
- [x] Fix the "Not Recommended" button on recommended listings take you to the listing, rather than greying out the card as expected
- [x] Change the behaviour of updating filters to either apply automatically on search, or through some graphical indicator if that's easier
- [x] And the spinner for low loading

Relates: #272

### PR DESCRIPTION
**Pull request by ChloeZacharias**
# Description

- [X] Fix the defaults for the price filters should be null, rather than zero
- [X] Fix the "Not Recommended" button on recommended listings takes you to the listing, rather than greying out the card as expected
- [X] Change the behavior of updating filters to either apply automatically on search, or through some graphical indicator if that's easier
- [X] Add spinner for loading

Closes #274 

## Checklist
- [ ] The code includes tests if relevant
- [ ] I have *actually* self-reviewed my changes and done QA

### CODE REVIEW

**Review by CaelumD25 — APPROVED** [review]
Looks good to me! Covers all the issues we found with this on Thursday.

File: apps/frontend/src/components/filters.tsx [hunk 1]
```diff
@@ -83,19 +99,42 @@ const Filters = ({ filters, onFilterChange }: FiltersProps) => {
...
+      status: status,
+      searchType: type,
+      latitude: latitude,
+      longitude: longitude,
+    });
   };
 
   const handleStatusChange = (event: SelectChangeEvent<string>) => {
     setStatus(event.target.value);
+    onFilterChange({
```
Comment (sejal-agarwal) [inline apps/frontend/src/components/filters.tsx:115]: Similar to above comment: 

```
onFilterChange({
...filterState,
status: newStatus
});
```

File: apps/frontend/src/components/filters.tsx [hunk 2]
```diff
@@ -83,19 +99,42 @@ const Filters = ({ filters, onFilterChange }: FiltersProps) => {
...
+      status: event.target.value,
+      searchType: type,
+      latitude: latitude,
+      longitude: longitude,
+    });
   };
 
   const handleTypeChange = (event: SelectChangeEvent<string>) => {
     setType(event.target.value);
+    onFilterChange({
```
Comment (sejal-agarwal) [inline apps/frontend/src/components/filters.tsx:127]:
```
onFilterChange({
...filterState,
searchType: newSearchType
});
```

**Review by sejal-agarwal — APPROVED** [review]

File: apps/frontend/src/pages/Homepage.tsx [hunk 3]
```diff
@@ -245,6 +222,14 @@ const Homepage = () => {
...
           </>
         )}
+        {!searchCompleted && listingObjects.length === 0 ? (
+          <Spinner text="Loading listings..." />
+        ) : null}
+        {searchCompleted && listingObjects.length === 0 ? (
+          <Typography variant="h6" component="h3" gutterBottom>
+            No Results Found
+          </Typography>
+        ) : null}
```
Comment (Scott-Kenning) [inline apps/frontend/src/pages/Homepage.tsx:232]:
```suggestion
        {listingObjects.length === 0 && (searchCompleted ? ... : ...)}
```

File: apps/frontend/src/components/Spinner.tsx [hunk 4]
```diff
@@ -0,0 +1,65 @@
+import CircularProgress from "@mui/material/CircularProgress";
```
Comment (Scott-Kenning) [inline apps/frontend/src/components/Spinner.tsx:1]: Is this component actually needed? In theory the loading state should be handled by whatever component is loading. And having the timeout here instead of on the request is also not how this should be done, as its not actually representative of the loading. And if an automatic timeout is being set, 40 seconds is way too long. 3-5 seconds is a more appropriate timeout

File: apps/frontend/src/components/Spinner.tsx [hunk 5]
```diff
@@ -0,0 +1,65 @@
...
+          justifyContent="center"
+          sx={{ marginTop: "40px" }}
+        >
+          <Grid item>
+            <CircularProgress size="40px" />
+          </Grid>
+          <Grid item sx={{ textAlign: "center" }}>
+            <Typography variant="h5">Hang with us</Typography>
+            <Typography variant="h6">{text}</Typography>
+          </Grid>
```
Comment (Scott-Kenning) [inline apps/frontend/src/components/Spinner.tsx:36]: If you do decide to keep this component, this is the only difference between the 2 states, so you can just have conditionals here on the spinner and the text

File: apps/frontend/src/components/filters.tsx [hunk 6]
```diff
@@ -49,10 +49,14 @@ const Filters = ({ filters, onFilterChange }: FiltersProps) => {
...
     if (event.target.value === "") {
       setPriceError("");
+      setMinPrice(null);
     } else if (!regex.test(event.target.value)) {
       setPriceError(
         "This price is not valid, please make sure the value is positive and in the form xx.xx",
       );
+    } else if (newMinPrice === null) {
+      setPriceError("");
+      setMinPrice(null);
```
Comment (Scott-Kenning) [inline apps/frontend/src/components/filters.tsx:59]: What is the case where newMinPrice is null and not ""?

File: apps/frontend/src/components/Spinner.tsx (hunk 4 above)
Comment (CaelumD25) [reply apps/frontend/src/components/Spinner.tsx:1]: The search/recommendation endpoint has taken over 30 seconds in the past to respond, so the default timeout on our axios requests is now 40 seconds until timeout. I know that this isn't technically ideal, but having a simple spinner makes the website look better and provides the user with some information other than a blank screen which may seem like a website failure to many users. 

The way it's set up now, it requires minimal effort to add it to our existing pages so I'd like to keep it like this if possible.

File: apps/frontend/src/components/filters.tsx (hunk 6 above)
Comment (ChloeZacharias) [reply apps/frontend/src/components/filters.tsx:59]: Since the number is accepted in a text box when nothing is entered the `event.target.value` is "" but the minPrice can not hold that value so when a search happens and I am setting the value to null to show the empty string. This is why I am checking both.

File: apps/frontend/src/pages/Homepage.tsx (hunk 3 above)
Comment (ChloeZacharias) [reply apps/frontend/src/pages/Homepage.tsx:232]: updated

File: apps/frontend/src/components/filters.tsx (hunk 2 above)
Comment (ChloeZacharias) [reply apps/frontend/src/components/filters.tsx:127]: Changed

File: apps/frontend/src/components/filters.tsx (hunk 1 above)
Comment (ChloeZacharias) [reply apps/frontend/src/components/filters.tsx:115]: Changed

File: apps/frontend/src/components/filters.tsx [hunk 7]
```diff
@@ -83,19 +99,42 @@ const Filters = ({ filters, onFilterChange }: FiltersProps) => {
       const priceValue: number = +event.target.value;
       setMaxPrice(priceValue >= 0 ? priceValue : priceValue * -1);
     }
-    setMaxPrice(event.target.value ? Number(event.target.value) : null);
+    setMaxPrice(newMaxPrice === null ? null : +newMaxPrice);
+    onFilterChange({
+      minPrice: minPrice,
```
[the remark this answers is not in the document]
Comment (ChloeZacharias) [reply apps/frontend/src/components/filters.tsx:104]: changed

File: apps/frontend/src/components/Spinner.tsx (hunk 5 above)
Comment (CaelumD25) [reply apps/frontend/src/components/Spinner.tsx:36]: I tried it a few ways and I thought the way it is now was the simplest to read.

File: apps/frontend/src/components/filters.tsx [hunk 8]
```diff
@@ -83,19 +99,42 @@ const Filters = ({ filters, onFilterChange }: FiltersProps) => {
...
+      maxPrice: event.target.value === "" ? null : +event.target.value,
```
[the remark this answers is not in the document]
Comment (ChloeZacharias) [reply apps/frontend/src/components/filters.tsx:105]: This was the easiest for me to read when debugging I might keep it this way since it is not a big change, incase I need to debug more in the future

File: apps/frontend/src/components/filters.tsx [hunk 9]
```diff
@@ -83,19 +99,42 @@ const Filters = ({ filters, onFilterChange }: FiltersProps) => {
       const priceValue: number = +event.target.value;
       setMaxPrice(priceValue >= 0 ? priceValue : priceValue * -1);
     }
-    setMaxPrice(event.target.value ? Number(event.target.value) : null);
+    setMaxPrice(newMaxPrice === null ? null : +newMaxPrice);
```
[the remark this answers is not in the document]
Comment (ChloeZacharias) [reply apps/frontend/src/components/filters.tsx:102]: This was the easiest for me to read when debugging I might keep it this way since it is not a big change, incase I need to debug more in the future

File: apps/frontend/src/components/filters.tsx (hunk 2 above)
Comment (ChloeZacharias) [reply apps/frontend/src/components/filters.tsx:115]: I ended up not changing these because the way java seems to be updating it is not getting the correct values when making multiple updates quickly
