### PR TITLE
Sprint 2 feedback fixes

### LINKED ISSUE #505: Fix Sprint 2 Issues
## Describe the bug

Issues found:
- For empty my listings 404 http code is returned, not handled properly on FE. 
- Create listings form:
  Shows validation error in title field on page load      without touching the form.
  Validation works only for title field, If i fill only the title field and keep other fields empty the form is submitted and the api request is sent with error returned as 400,however it is not shown to the user.
- Responsiveness and general UI can be improved on messaging page

Overall very good job product feels very high quality and most edge cases are covered.

### PR DESCRIPTION
**Pull request by CaelumD25**
# Description
Fixed the majority of issues that the TA had on the last sprint... I think...

## Made create/edit listing more responsive 
image
_Also removed validation on load_

image

2024-07-25 23 37 53 localhost ca0fc0adabaa

## Added borders and more indicative colors to the messages page
image
_although I have no idea why the TA doesn't think it's responsive_

## Fixed the mylistings page to use the new format
2024-07-25 23 39 18 localhost be951eb1ebfd

### Backend Issues Identified:
  - Description is required to create a listing
  - A non-zero price is required for a listing
  - Listing prices get rounded to nearest whole number

----

### Future Work
In another PR, every console.error will either need to be removed or modified to say everything is fine, even if it isn't

Closes #505 
See this issue for the TA's feedback 

## How to Test
Run the application or run npm test

## Checklist
- [x] The code includes tests if relevant
- [ ] I have *actually* self-reviewed my changes and done QA

### CODE REVIEW

File: apps/frontend/src/pages/CreateListing.tsx [hunk 1]
```diff
@@ -76,10 +74,16 @@ const CreateListing = () => {
     submissionEvent,
   ) => {
     submissionEvent.preventDefault();
-    if (!priceError && !titleError && !sent) {
+    console.log(newListingObject);
```
Comment (sejal-agarwal) [inline apps/frontend/src/pages/CreateListing.tsx:77]: I think we can remove this console log

File: apps/frontend/src/pages/CreateListing.tsx [hunk 2]
```diff
@@ -76,10 +74,16 @@ const CreateListing = () => {
...
+    if (!titleError && !sent) {
       // In order to make sure that the images are retrieved before submitting
       const successImages: boolean = await asyncListingImageWrapper();
 
+      if (!newListingObject.listing.title) {
+        setTitleError("Please enter a title");
```
Comment (sejal-agarwal) [inline apps/frontend/src/pages/CreateListing.tsx:83]: I may have missed it, but is there any error shown for not entering a price?

File: apps/frontend/src/pages/EditListing.tsx [hunk 3]
```diff
@@ -336,103 +347,128 @@ const EditListing = () => {
...
+                          onClick={clearImages}
                         >
-                          No images uploaded yet, these images will overwrite
-                          the current ones.
-                        </Typography>
+                          Clear Images
+                        </Button>
                       ) : (
-                        <Carousel imageURLs={listingImages} />
+                        <></>
```
Comment (sejal-agarwal) [inline apps/frontend/src/pages/EditListing.tsx:423]: This can be removed

**Review by sejal-agarwal — APPROVED** [review]
You're an absolute superstar Caelum!! Thank you so much!! 😁

File: apps/frontend/src/pages/CreateListing.tsx (hunk 2 above)
Comment (CaelumD25) [reply apps/frontend/src/pages/CreateListing.tsx:83]: So I got rid of it because I have it registering an empty field as 0, I also made it so the input cannot be anything but acceptable values, if think I should add it back though, that shouldn't be much of an issue!

File: apps/frontend/src/pages/EditListing.tsx (hunk 3 above)
Comment (CaelumD25) [reply apps/frontend/src/pages/EditListing.tsx:423]: Fixed!
